#!/bin/bash
# Init script for McMyAdmin on Debian Linux
# Original script by Markus Ewald
# Modified by bitstacker 
 
### BEGIN INIT INFO
# Provides:   minecraft
# Required-Start: $local_fs $remote_fs
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:    Minecraft server
# Description:    Starts the minecraft server
### END INIT INFO
 
# Settings
USER="minecraft"
MCDIR="/opt/minecraft/"
 
. /lib/lsb/init-functions
mc_start() {
	log_daemon_msg "Starting minecraft server"
	if ps ax | grep SCREEN | grep -v grep | grep minecraftd > /dev/null 
	then
		log_progress_msg "Minecraft is already running"
		log_end_msg 1
	else
		log_progress_msg "No running Server found. Starting a new one..."
  		env TERM="xterm" \
		start-stop-daemon \
			--start \
			--make-pidfile \
			--pidfile /var/run/minecraft.pid \
			--background \
			--chuid minecraft \
			--name minecraft \
			--chdir $MCDIR \
			--exec /usr/bin/screen -- -D -m -S minecraftd /opt/minecraft/MCMA2_Linux_x86_64
		log_end_msg 0
	fi
}
 
mc_stop() {
	log_daemon_msg "Stopping minecraft server"
 	su - minecraft -c "screen -p 0 -S minecraftd -X eval 'stuff /quit\015'" > /dev/null
	sync
	sleep 5
 	if [ -e /var/run/minecraft.pid ]; then
		read PID < /var/run/minecraft.pid
		if [ -d /var/run/${PID} ]; then
			log_progress_msg "Normal shutdown not successfull, forcing"
			start-stop-daemon \
				--stop \
				--signal 15 \
				--pidfile /var/run/minecraft.pid
    		fi
  	fi
	if ps ax | grep SCREEN | grep -v grep | grep minecraftd > /dev/null
	then
		log_progress_msg "Minecraft is still running"
		log_end_msg 1
	else
		log_progress_msg "Found no running minecraft"
		log_end_msg 0
	fi
}
 
case "$1" in
  start)
    mc_start
    ;;
  stop)
    mc_stop
    ;;
  *)
    echo "Usage: /etc/init.d/minecraft {start|stop}"
    echo "       ...and hope that it works!"
    ;;
esac

